### ISSUE TITLE
Remove globby as dependency

### ISSUE THREAD

**Issue by tunnckoCore** [azz/get-monorepo-packages#4]
I don't think it is needed, at all. Also, it's slow no matter it uses `fast-glob` under the hood.

I recently needed and implemented such thing. I remove the `/*` from given workspaces, then just readdir.

```js
pkg.workspaces
    .map((x) => x.slice(0, -2))
    .filter(Boolean)
    .reduce((acc, ws) => {
      const workspace = path.join(cwd, ws);
      const packages = fs
        .readdirSync(workspace)
        .map((dir) => {
          const pkgDir = path.join(workspace, dir);
          const pkgJsonPath = path.join(pkgDir, 'package.json');

          return { pkgDir, pkgJsonPath };
        })
        .map(({ pkgDir, pkgJsonPath }) => {
          // eslint-disable-next-line global-require, import/no-dynamic-require
          const pkgJson = require(pkgJsonPath);
          return { pkgDir, pkgJson };
        });

      return acc.concat(packages);
    }, [])
```

**Comment by azz** [comment]
Do you have any performance benchmarks?  Doing a `x/*` glob should be very quick.

**Comment by tunnckoCore** [comment]
Benchmarks are on the fast-glob repo. And as I understand they are as of globby@8, recently v9 was released but I think nothing important that impacts benchmarks, so I don't think it will be faster than v8.

**Comment by tunnckoCore** [comment]
Also, generally speaking, it's not needed. It may be quick, but the most common case is `/*` and not more complex glob anyway.

**Comment by azz** [comment]
Maybe the most common, but not the only possible value. I'd rather this library be correct than fast, as it is generally used for dev tooling at process boot, and is not in any critical code paths.

**Comment by tunnckoCore** [comment]
No matter what, things should always be optimized for at least the 90% of the cases ("most common").

Anyway. Such mistakes are the reason why tooling is in that state currently.
